package day_51_abstraction;

public class Abstraction {
    /*
Abstraction:
   Abstraction is a process of hiding the implementation details from the user
   -is concentrating on WHAT TO DO, instead of HOW TO DO
   -is concentrating on essential parts rather than specifics
   -is a way to hide implementation and just display functionality
_____________________________________________
Where we do write implementation for abstract method in abstract class?
Subclasses of abstract class are responsible for implementation of
all abstract class.

ABSTRACT CLASS>CONCRETE CLASS
CONCRETE CLASS--IS A NON-ABSTRACT CHILD CLASS OF ABSTRACT CLASS
CONCRETE CLASS-PROVIDE IMPLEMENTATION FOR ALL ABSTRACT METHODS IN SUPER CLASS

ABSTRACT METHOD--> METHOD WITHOUT BODY/IMPLEMENTATION.
HIDE IMPLEMENTATION.
              -->IT IS CREATED USING ABSTRACT KEYWORD AND NO CURLY BRACES FOR METHOD,
              INSERT SEMICOLON
              -->IT CAN BE WRITTEN IN ABSTRACT CLASSES AND INTERFACE
              --?SUB CLASS WHICH IS NOT ABSTRACT IS RESPONSIBLE FOR IMPLEMENTING
              ABSTRACT METHODS

 BENEFIT OF ABSTRACTION
               -->IS ABILITY TO FOCUS ON MAIN BEHAVIOR AND DESIGN WITHOUT
               WORRYING ABOUT IMPLEMENTATION DETAILS
               -->GIVING CHANCE TO HAVE HIGHER LEVEL OF IDEA
               -->ABSTRACT CLASS WILL BE USED AS A BASE CLASS FOR ALL SUBCLASSES
               -->EASIER TO MAINTAIN AND CENTRALIZE CLASSES
ABSTRACT CLASS:
   -CAN NOT INSTANTIATE IT
   -CAN DEFINE ABSTRACT METHODS:
         METHOD WITHOUT BODY
   -CAN DEFINE NON-ABSTRACT METHOD:
IN ABSTRACT CLASS, WE CAN WRITE REUSABLE VARIABLES AND METHODS FOR ALL SUB CLASSES.

SUMMARY:
    -FOCUS ON WHAT TO DO INSTEAD OF HOW TO DO
    -HIDE IMPLEMENTATION FROM END USERS
    -FOCUS ON ESSENTIAL PARTS WITHOUT WORRYING ON IMPLEMENTATION
    -------------------------------------------------
ABSTRACTION ACHIEVED IN JAVA 2 WAYS
    -ABSTRACT CLASS
    -INTERFACE
    ----------------------------------------------------
 ABSTRACT CLASS
     -ABSTRACT KEY WORD IS USED TO WRITE ABSTRACT CLASS
     -CAN NOT BE INSTANTIATED/CANNOT CREATE OBJECT
 CONCRETE CLASS-->CLASS IS RESPONSIBLE FOR IMPLEMENTATION/OVERRIDING OF ALL ABSTRACT CLASS









    */
}
