package day_56_exceptions;

public class ExceptionHandling {
    /*
    IN JAVA, EXCEPTIONS ARE ERRORS THAT HAPPEN DURING RUN TIME.
    YOU HAVE CODE WITH 200 LINES , THAT IS RUNNING AND AT LINE 105 SOME ERROR HAPPENS.

    2 OPTION:
     ----YOU LET YOUR CODE FAILING AND STOP
     ----YOU CAN HANDLE THE EXCEPTION PROGRAMMATICALLY

     JAVA PROGRAM WRITING AND EXECUTION PROCESS:
     WE WRITE OUR CODE AND SAVE IT WITH .JAVA EXTENSION.
     HELLOWORLD.JAVA-->COMPILER-->HELLOWORLD.CLASS-->RUN
     AS WE SEE IN THE FLOW, IT NEEDS TO BE COMPILED FIRST THEN
     EXECUTED. SO COMPILER WILL CHECK EVERYTHING:SYNTAX,DATA TYPES,
     FOR EX: (INT N="JAVA")/ERROR ETC BEFORE COMPLETING COMPILATION PROCESS.
     IF COMPILER SEES SOMETHING IS WRONG, WE WILL SEE COMPILER ERROR.
     COMPILE ERROR -->HAPPENS DURING COMPILE PROCESS AND IT IS DUE TO
     PROGRAMMER'S MISTAKE. WE NEED TO FIX THEM FOR OUR PROGRAM
     TO BE ABLE TO RUN SUCCESSFULLY. THEY ARE NOT EXCEPTIONS.

     WHEN YOUR CODE IS RUNNING, IT WILL RUN TOP TO BOTTOM, LINE BY LINE.WHEN
     JAVA SEES A LINE THAT HAS ERROR, IT WILL THROW EXCEPTION, RUNTIME EXCEPTION.

     COMPILE ERROR--ERROR DURING COMPILE PROCESS
     EXCEPTION--ERROR DURING RUNNING PROCESS.
     ---------------------------
     SINCE JAVA IS OBJECT ORIENTED LANGUAGE,EVEN EXCEPTIONS
     ARE ALSO OBJECTS THAT ARE CREATED.
     FOR EACH EXCEPTION TYPE IN JAVA, THERE IS A CLASS.
     WHENEVER ERROR HAPPENS DURING RUNTIME, OBJECT IS CREATED A MATCHING CLASS.

     IF YOUR CODE IS READING FROM INVALID INDEX, THEN OBJECT FROM
     ArrayIndexOutOfBoundsException CLASS IS CREATED AND THROWN.

     ArrayIndexOutOfBoundsException,ArithmeticException ARE CLASSES IN JAVA, AND
     WHEN WE HAD MATCHING ISSUES IN OUR CODE DURING RUNTIME, OBJECT IS CREATED FROM THOSE
     CLASSES AND THROWN, IT CAUSED THE PROGRAM TO STOP.

     ArrayIndexOutOfBoundsException-IS THROWN WHEN OUR CODE TRIES TO ACCESS INVALID INDEX.
     OBJECT FROM THIS CLASS IS THROWN
     ArithmeticException-IS THROWN DURING RUNTIME WHEN OUR CODE DIVIDES BY ZERO.

     SINCE WE KNOW THAT, EXCEPTION ARE ALSO OBJECTS FROM CLASSES, WE CAN LOOK AT THEIR
     HIERARCHY.
     IN JAVA, EXCEPTION CLASSES USE INHERITANCE. THERE ARE MANY CLASSES FOR EXCEPTIONS IN JAVA,
     WE JUST NEED TO LEARN FEW.
     THERE ARE DIFFERENT MAIN TYPE OF EXCEPTIONS.
     _____________________________________

     HOW TO HANDLE EXCEPTIONS IN JAVA?
     TRY CATCH STATEMENT.














    */
}
