package day_47_inheritance_access_modifier;

public class InheritanceConstructor {
    /*
    INHERITANCE+CONSTRUCTOR
    - SUPER CLASS CONSTRUCTOR RUNS BEFORE SUB CLASS CONSTRUCTOR
    -SUPER() KEYWORD IS USED TO CALL SUPER CLASS CONSTRUCTOR
    -SUPER(PARAM) IT WILL CALL THE MATCHING SUPER CLASS CONSTRUCTOR
    -IF WE DON'T ADD SUPER() KEYWORD, COMPILER ADDS THAT
    -OBJECT CLASS IS ROOT, OR PARENT CLASS FOR ALL CLASSES IN JAVA
    -EXTENDS OBJECT IS AUTOMATICALLY ADDED  BY COMPILER IF YOUR CLASS DOES NOT
    EXTEND ANY OTHER CLASS
  */
}
