package day_60_collections_2;

public class VectorDemo {
    /*
    Vector is another array based List implementation.
    Similar to ArrayList.
    Vector is THREAD-SAFE.
    Vector is SYNCHRONIZED
    MULTI THREADING IS ABILITY TO RUN OUR JAVA PROGRAM MULTIPLE TIMES CONCURRENTLY/AT A SOMETIME
    THREAD-SAFETY MEANS WHEN MULTIPLE THREAD TRY TO ACCESS A SEMA RESOURCES( VARIABLES, ARRAYLIST OBJECT, EXC)
    AT A SOME TIME, JAVA WILL LOCK IT FOR ONW THREAD AT A TIME.
    WHEN ONE THREAD IS ACCESSING IT, OTHERS WILL WAIT.
    SYNCHRONIZED KEYWORD IS USED TO ACHIEVE THREAD SAFETY IN JAVA.
    WHAT IS THE DIFFERENCE BETWEEN ARRAY LIST AND VECTOR?
    BOTH OF THEM ARRAY BASED COLLECTION THAT IMPLEMENTS LIST INTERFACE
    VECTOR IS THREAD SAFE IT IS SYNCHRONIZED.
    ARRAY LIST IS NOT THREAD SAFE, THAT'S WHY IT IS FASTER.
    BOTH KEEP ORDERING AND ALLOW DUPLICATES.




    */
}
