package day_58_exception_3;

public class FinalVSFinallyVSFinalize {
    /*

    FINAL:
       KEY WORD
       FINAL VARIABLES IS CONSTANT, VARIABLE THAT VALUE CANNOT BE CHANGED.
       FINAL METHOD CAN NOT BE OVERRIDDEN.
       FINAL CLASS CAN NOT BE INHERITED

    FINALLY:
       BLOCK
       FINALLY BLOCK IS USED WITH TRY CATCH EXCEPTION HANDLING.
       CODE IN FINALLY BLOCK ALWAYS EXECUTED REGARDLESS EXCEPTION
       WAS HANDLED/THROWN OR NO.
    FINALIZE:
       METHOD
       FINALIZE IS A METHOD IN OBJECT CLASS.
       IS USED TO PERFORM SOME CLEANUP STATEMENTS BEFORE
       OBJECT IS GARBAGE COLLECTED.

    */
}
