package day_59_exception_end_collection.collcetion_intro;

public class DataStructuresInJava {
    /*
    DATA STRUCTURES-->ORGANIZING DATA IN A CERTAIN WAY SO THAT WE CAN EASILY MANAGE IT AND USE IT
    1.ARRAYS ARE BUILT IN CORE DATA STRUCTURE, COLLECTION OF DATA OF SAME TYPE, FIXED SIZE.
    2.COLLECTION FRAMEWORK-->INTERFACES AND IMPLEMENTING CLASSES THAT COMES WITH JAVA
    3.MAP AND HASHMAP-->DOES NOT EXTEND COLLECTION. BUT OVER ALL IT IS PART OF COLLECTION FRAMEWORK


    1.Array
    2.Collection FrameWork
    3.Map
    */
}
